dados_path: "dados/"
raw_bucket: "eedb-022-2026-grupo03-raw"
trusted_bucket: "eedb-022-2026-grupo03-trusted"
delivery_bucket: "eedb-022-2026-grupo03-delivery"
redshift_host: "eedb-022-grupo03.ct3ja6yhrepn.us-east-1.redshift.amazonaws.com"
redshift_port: 5439
redshift_database: "dev"
redshift_user: "admin"
redshift_password: "Admin1234"
